// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQKFWNNvf_9H_-YzSyPUlQ4kxtnglZps',
    appId: '1:846324298054:web:0d81a15fb0dd97f1e27547',
    messagingSenderId: '846324298054',
    projectId: 'almacenamiento-dca5b',
    authDomain: 'almacenamiento-dca5b.firebaseapp.com',
    storageBucket: 'almacenamiento-dca5b.firebasestorage.app',
    measurementId: 'G-F43TCT4Q57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh8_e6XQRes4Z9jr4xFsPSyIr4lDW7_IA',
    appId: '1:846324298054:android:df53c52754824aa1e27547',
    messagingSenderId: '846324298054',
    projectId: 'almacenamiento-dca5b',
    storageBucket: 'almacenamiento-dca5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0pBXR9uxMCaucfORKmn3fWaIWM1vqtU',
    appId: '1:846324298054:ios:500e9f7e7d6994a5e27547',
    messagingSenderId: '846324298054',
    projectId: 'almacenamiento-dca5b',
    storageBucket: 'almacenamiento-dca5b.firebasestorage.app',
    androidClientId: '846324298054-juc00aer08iqmdpm8h3s6culvucvk83d.apps.googleusercontent.com',
    iosClientId: '846324298054-tbpd73h75dcndld8tf36qpiqoehr5sua.apps.googleusercontent.com',
    iosBundleId: 'com.example.ag3Almacenamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA0pBXR9uxMCaucfORKmn3fWaIWM1vqtU',
    appId: '1:846324298054:ios:500e9f7e7d6994a5e27547',
    messagingSenderId: '846324298054',
    projectId: 'almacenamiento-dca5b',
    storageBucket: 'almacenamiento-dca5b.firebasestorage.app',
    androidClientId: '846324298054-juc00aer08iqmdpm8h3s6culvucvk83d.apps.googleusercontent.com',
    iosClientId: '846324298054-tbpd73h75dcndld8tf36qpiqoehr5sua.apps.googleusercontent.com',
    iosBundleId: 'com.example.ag3Almacenamiento',
  );
}
